server:
  port: 8080

#log-path: /opt/tomcat/customlogs/
log-path:  C:/logs/
market_check_url: http://api.marketcheck.com/v2/decode/car/neovin/
market_check_url_suffix: /specs?
api_key: api_key=hTUx9slxqOdFy4WQG7CRTuAIvC38A5mJ
host : marketcheck-prod.apigee.net
image_folder_path: D:/images/
video_folder_path: D:/images/
profile_pic_path: C:/profilepics/
#image_folder_path: images
#video_folder_path: videos
properties_path : /home/factory/properties/
#profile_pic_path: profilepics
file_size: 500000000
#saved_pdf_Path: pdf
saved_pdf_Path: D:/pdf/
get-link: https://services-test.keyassure.live/appraisal/getpic1?pic1=
appraisal_form_path: src\\main\\resources\\AppraisalFormJR.jrxml
whlsale_tmp_path: src\\main\\resources\\whlSaleBuyerOdr.jrxml
vehicle_rep_path: src\\main\\resources\\vehicleReport.jrxml
identityServer_userCreation: https://is-test.keyassure.live/t/carbon.super/scim2/
paramValue: 3be77329-6d2d-4a72-a6a1-a6fbb02d0809
access_key: IJNKK0VI1KN7268AVRH2
secret : q4M7yWvLhpkpIameiiMB6PmmphcEjACOUAbv1oBs
amazonS3_url : dal-storage.hostwinds.net/keyassure-test/
jrXmlPics: https://dal-storage.hostwinds.net/swift/v1/c652a066a7e14f32b4dfd9981ccac3ce/keyassure-test/images/
identityServerAuth: YWRtaW46YWRtaW4=
payment_server: secure.nmi.com
payment_port: 443
payment_path: https://secure.nmi.com/api/transact.php

cron.schedule.expression: "0 */50 * * * *"
cron.schedule.everyDay: "0 0 20 * * *"
cron.schedule.onceInMonth: "0 0 0 6 * *"
cron.schedule.expression.autoBid: "0 */2 * * * *"
#countdownClockOfMin: 30
countdownClockOfMin: 5

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  datasource:
    driver-class-name: org.postgresql.Driver
    password: Massil@123
    url: jdbc:postgresql://localhost:5432/Factory_db
    username: postgres
#    url: jdbc:postgresql://hwsrv-1076442.hostwindsdns.com:5438/keyassure
#    username: keyassureadmin
#    password: HxH50y8rpp$j

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
      id:
        new_generator_mappings: false
    properties:
      hibernate:
        default_schema: factory_db
        search:
          backend:
            uris: http://127.0.0.1:9200
#            uris: http://10.175.1.20:9200
          schema_management:
            strategy: create-or-update
            minimal_required_status: yellow
      org:
        hibernate:
          envers:
            do_not_audit_optimistic_locking_field: false
            default_schema: factory_aud
            revision_field_name: REV
            revision_type_field_name: REV_TYPE
    show-sql: true

  mail:
    host: mail.factorykeyassure.com
    password: TIbMFm(#2Wn.
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          ssl:
            enable: false
          starttls:
            enable: true
        transport: 
          protocol: smtp
    protocol: smtp
    test-connection: false
    username: system@factorykeyassure.com
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB


management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html

org:
  jobrunr:
    background-job-server:
      poll-interval-in-seconds: 5
      enabled: true
    dashboard:
      enabled: true
      port: 8001


#hibernate:
#  search:
#   backend:
#     hosts: 10.175.1.20:9200
#     protocol: http
#     uris: http://10.175.1.20:9200/
#   schema_management:
#    strategy: create


logging:
  config: classpath:logback-test1.xml


