server:
  port: 8082

log-path: /opt/tomcat9/customlogs/
market_check_url: http://api.marketcheck.com/v2/decode/car/neovin/
market_check_url_suffix: /specs?
api_key: api_key=hTUx9slxqOdFy4WQG7CRTuAIvC38A5mJ
host : marketcheck-prod.apigee.net
image_folder_path: images
video_folder_path: videos
properties_path : /home/factory/properties/
profile_pic_path: profilepics
file_size: 500000000
saved_pdf_Path: pdf
#get-link: https://services-test.keyassure.live/appraisal/getpic1?pic1=
appraisal_form_path: src\\main\\resources\\AppraisalFormJR.jrxml
whlsale_tmp_path: src\\main\\resources\\whlSaleBuyerOdr.jrxml
vehicle_rep_path: src\\main\\resources\\vehicleReport.jrxml
identityServer_userCreation: https://is.keyassure.live/t/carbon.super/scim2/
paramValue: ff9562ca-d4df-4754-abe1-847c81814b00
access_key: IJNKK0VI1KN7268AVRH2
secret : q4M7yWvLhpkpIameiiMB6PmmphcEjACOUAbv1oBs
amazonS3_url : dal-storage.hostwinds.net/keyassure/
jrXmlPics: https://dal-storage.hostwinds.net/swift/v1/c652a066a7e14f32b4dfd9981ccac3ce/keyassure/images/
identityServerAuth: YWRtaW46eVN3cVRnSDE2NFJp


cron.schedule.expression: "0 */50 * * * *"

spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://142.11.201.154:5438/keyassure
    username: keyassureadmin
    password: G33vR1776Hbj
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: none
      id:
        new_generator_mappings: true
    properties:
      hibernate:
        default_schema: factory_db
      org:
        hibernate:
          envers:
            do_not_audit_optimistic_locking_field: false
            default_schema: factory_aud
            revision_field_name: REV
            revision_type_field_name: REV_TYPE
    show-sql: true

  mail:
    host: mail.factorykeyassure.com
    password: TIbMFm(#2Wn.
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
        transport: 
          protocol: smtp
    protocol: smtp
    test-connection: false
    username: system@factorykeyassure.com
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB


management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
        exclude: "env,beans"



swagger:
  enable: true

springfox:
  documentation:
    swagger-ui:
      base-url: /

